### PR TITLE
Jsk apc fixed rebase for knorh55

### PR DESCRIPTION
**Pull request by k-okada**
this PR contains
https://github.com/ipa320/softkinetic/pull/62 and https://github.com/ipa320/softkinetic/pull/63 + alpha

Please check if you want to use 
- depth_registered/points ( pointcloud re-published from rgb optical frame)
  or
- depth_registered_downsample/points_filtered (filter out the outliner, we need to use voxel grid to do this, so size of point cloud may differ from original one)

size of color image is 1280x720, depth image is 320x240 and published registered point cloud (depth_registered/points) is 1280x720, is this OK? or do you want to registered cloud of size 320x240?

Cc: @yuyu2172

### CODE REVIEW

**Comment by knorth55** [comment]
i think 320x240 is better because if you use 1280x720, the point cloud data contains a lot of "NaN" data, right?

**Comment by k-okada** [comment]
It does not seems so, Please double check

2016年6月9日木曜日、Shingo Kitagawanotifications@github.comさんは書きました:

> i think 320x240 is better because if you use 1280x720, the point cloud
> data contains a lot of "NaN" data, right?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/knorth55/softkinetic/pull/2#issuecomment-224858544,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAeG3DzSWiuvai_rGnB8z6mmMvI7ehpnks5qJ-xHgaJpZM4Ix1aQ
> .

## 

## 

◉ Kei Okada

**Comment by wkentaro** [comment]
@k-okada 
Do we need to calibrate here?: https://github.com/knorth55/softkinetic/pull/2/files#diff-08c25eea1e9d28cb48551702d689db21R35
image

**Comment by k-okada** [comment]
> Do we need to calibrate here?: https://github.com/knorth55/softkinetic/pull/2/files#diff-08c25eea1e9d28cb48551702d689db21R35

it seems so, please find the parameter, I'm testing on 9/10 camera,

**Comment by k-okada** [comment]
@knorth55>  i think 320x240 is better because if you use 1280x720, the point cloud data contains a lot of "NaN" data, right?

you can get 320x240 points with https://github.com/knorth55/softkinetic/pull/1/commits/075d7553b2981439a41b38226b82ef686ee7da0b
you have to use latest jsk_recogniton, until we release 0.3.22

but I do no know which is the better 320 or 720

Cc: @yuyu2172

**Comment by k-okada** [comment]
@wkentaro 

if we need more precise calibration, we need to update yaw angle between rgb_frame and depth_frame

screenshot from 2016-06-10 01 08 08
screenshot from 2016-06-10 01 08 28

**Pull request merged**
